# Generated by Django 5.2.8 on 2025-12-10 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Continentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=70, unique=True)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paises', to='destinos.continente')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ['pais'],
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100, unique=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='destinos.pais')),
            ],
            options={
                'verbose_name_plural': 'Destinos',
                'ordering': ['pais', 'destino'],
            },
        ),
    ]
