# Generated by Django 5.2.8 on 2025-12-10 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, default='viajes/default.png', null=True, upload_to='viajes')),
                ('fecha_viaje', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Viaje')),
                ('publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Publicacion')),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinos.destino')),
            ],
            options={
                'verbose_name_plural': 'Viajes',
                'ordering': ['titulo', 'destino', '-fecha_viaje'],
            },
        ),
    ]
