# Generated by Django 5.2.8 on 2025-12-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_viaje',
            field=models.DateTimeField(verbose_name='Fecha Viaje'),
        ),
    ]
