# Generated by Django 5.2.8 on 2025-12-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_alter_viaje_fecha_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_viaje',
            field=models.DateTimeField(default='2000-01-01', verbose_name='Fecha Viaje'),
        ),
    ]
