# Generated by Django 5.2.8 on 2025-12-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_alter_viaje_fecha_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='destacado',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
