# Generated by Django 5.2.8 on 2025-12-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_viaje_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='publicacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Publicacion'),
        ),
    ]
